### ISSUE TITLE
KeyError: 'configuration_status'

### ISSUE THREAD

**Issue by Fr0zenflame** [marcinbojko/foreman_exporter#1]
Hallo Marcinbojko,

I am trying to scrape our foreman test environment .
At first we ran into some issues with permissions but this is fixed now.
Currently I am running into an error which seem to reside inside the container.

**I am using the following setup:**
- Docker Compose version v2.17.2
- Container version: marcinbojko/foreman_exporter:latest
- OS: "Ubuntu 18.04.6 LTS"
- Foreman 2.4.1

_** anonymised URL with HTTPS://FQDN.NET_

forman_acc_exporter  | REQUEST_URI        = HTTPS://FQDN.NET
forman_acc_exporter  | REQUEST_HOSTNAME   = hostname
forman_acc_exporter  | REQUEST_USER       = <username>
forman_acc_exporter  | REQUEST_TLS_VERIFY = False
forman_acc_exporter  | REQUEST_TIMEOUT    = 60
forman_acc_exporter  | REQUEST_INTERVAL   = 120
forman_acc_exporter  | 2023-03-29 09:34:46.323434 Status request at HTTPS://FQDN.NET/api/status with code 200 took 0 seconds
forman_acc_exporter  | 2023-03-29 09:34:46.323479 Foreman version found at: HTTPS://FQDN.NET is 2.4.1
forman_acc_exporter  | 2023-03-29 09:34:47.136218 Hosts request at HTTPS://FQDN.NET/api/hosts with code 200 took 0 seconds
forman_acc_exporter  | 2023-03-29 09:34:47.435779 Dashboard request at: HTTPS://FQDN.NET/api/dashboard with code 200 took 0 seconds
forman_acc_exporter  | 2023-03-29 09:34:47.435823 Script version is 0.0.14
forman_acc_exporter  | 2023-03-29 09:34:47.435839 Starting http server at port 8000
forman_acc_exporter  | Traceback (most recent call last):
forman_acc_exporter  |   File "/app/foreman_exporter.py", line 318, in <module>
forman_acc_exporter  |     REGISTRY.register(RequestsHosts())
forman_acc_exporter  |   File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 40, in register
forman_acc_exporter  |     names = self._get_names(collector)
forman_acc_exporter  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
forman_acc_exporter  |   File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 80, in _get_names
forman_acc_exporter  |     for metric in desc_func():
forman_acc_exporter  |   File "/app/foreman_exporter.py", line 194, in collect
forman_acc_exporter  |     configuration_status = str(each['configuration_status'])
forman_acc_exporter  |                                ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
forman_acc_exporter  | KeyError: 'configuration_status'
forman_acc_exporter exited with code 1

`**docker-compose.yml**`
version: "3.8"
services:
  foreman_exporter:
    container_name: forman_acc_exporter
    image: marcinbojko/foreman_exporter:latest
    ports:
     - "8000:8000"
    env_file:
      ./foreman_acc_exporter.env

`**foreman_acc_exporter.env**`
FOREMAN_REQUEST_URI='HTTPS://FQDN.NET/'
FOREMAN_REQUEST_USER='<username>'
FOREMAN_REQUEST_PASSWORD='<password>'
FOREMAN_REQUEST_TLS_VERIFY=false
FOREMAN_REQUEST_TIMEOUT=60
FOREMAN_REQUEST_INTERVAL=120

**I also found an issue regarding in another GitHub project (frigate) which seem to be related (to me);**
https://github.com/blakeblackshear/frigate/discussions/5463

If you can elaborate/explain what is going wrong or make a fix :-) that would be great!
Thanks in advance, cheers

**Comment by marcinbojko** [comment]
Hi @Fr0zenflame 
Could you confirm your Foreman endpoint servers metrics?
That seems like a crash in python prometheus libraries, trying to get the data from foreman.

**Comment by Fr0zenflame** [comment]
Hi @marcinbojko ,


Thanks for your response.

I used an incorrect password in the .env to make sure the docker container stays UP, since it crashes.
I'll get (empty) metrics back.
When I entered the correct credentials but with incorrect permissions in the back-end I also get (empty) metrics back.
When I enter correct credentials with the correct permissions in the back-end the container crashes with the error (KeyError: 'configuration_status').

* I also tried it with my own account (all permissions).
* Furthermore when I do an API request under the account(s) in a browser, I also get metric data (see screenshot)

**(empty) metrics via curl to running container with invalid login (to prevent it from crashing);**
![image](https://user-images.githubusercontent.com/107129758/228483892-b439da24-baa1-4a40-accd-eef9fbdd69b5.png)

**Browser API call with correct credentials to foreman**
![image](https://user-images.githubusercontent.com/107129758/228485694-d2a46532-1d39-4932-ae50-7a32e2430b89.png)

**Comment by marcinbojko** [comment]
Hi @Fr0zenflame 
Let's try to see what are our results from your foreman. Could we check this?

```
curl -sk -u user:password https://foreman.sample.com/api/hosts|jq -r .results[].configuration_status  
```

replace please user, password and proper fqdn

**Comment by Fr0zenflame** [comment]
Hi Marcin,

**The result of your command:**
![image](https://user-images.githubusercontent.com/107129758/228569459-fb847926-c542-43df-a343-b2bbea335db7.png)

I was also experimenting with older versions of "prometheus_client" and at one point I was able to curl the metrics from the "foreman_exporter" container. But after I restarted the container the changes were gone and i'm not able to reproduce :-(

**Comment by marcinbojko** [comment]
Hi @Fr0zenflame 
The problem is, the current version of foreman_exporter doesn't work properly when status is not numeric. In some cases you have 'null', which confuses the exporter.
As a quick workaround, you can make sure all hosts have proper status (numeric).
I'll try to find some free time to add a check into exporter

**Comment by Fr0zenflame** [comment]
> Hi @Fr0zenflame
> The problem is, the current version of foreman_exporter doesn't work properly when status is not numeric. In some cases you have 'null', which confuses the exporter.
> As a quick workaround, you can make sure all hosts have proper status (numeric).
> I'll try to find some free time to add a check into exporter

Hi Marcin,

Thanks for your response.
Ill try to fix those values in our test/acceptance environment and confirm my findings as soon as I've done it.
Hopefully you (or we) can come up with a more permanent fix before going tot production ^^

**Comment by marcinbojko** [comment]
You can try this interim version pushed few minutes ago.
https://hub.docker.com/layers/marcinbojko/foreman_exporter/0.0.15-dev.1/images/sha256-18267f93ceba8d2cc91deb330017cc39ba974ef895545a429e5d9dece076db10?context=repo

**Comment by Fr0zenflame** [comment]
I'tried version "marcinbojko/foreman_exporter:0.0.15-dev.1" but unfortunately I still get the same error.

![image](https://user-images.githubusercontent.com/107129758/228776527-e41cabf8-a8fc-40ab-ace2-4c5382ec4122.png)

**Comment by marcinbojko** [comment]
Sorry, I need to debug further, trying to duplicate the issue on my foreman.

**Comment by marcinbojko** [comment]
Hi @Fr0zenflame 
Sorry, but currently I don't have much time to play with open source.
I've changed the logic for checks, so please try the new version 

https://hub.docker.com/layers/marcinbojko/foreman_exporter/0.0.15-dev.2/images/sha256-79464c46cd8aee885694d33605aa70c70fc31b0cebe1fb9d072247683c34c240?context=repo

**Comment by Fr0zenflame** [comment]
Hi Marcin,

Thnx for your reply.
I understand that open-source/hobby takes a lot of time and that work goes first ofc 😄

Unfortunately the dev2 version of your container still generates the same issue.
[cid:134b0bc8-147e-4af8-b586-d2504539fd5b]

Maybe I'am gonna make a custom branch and try to fix the script but like you I dont have a lot of time at the moment.
And im not an Python developer 😄 just know the basics 🙂

Kind regards,
Danny

________________________________
Van: marcinbojko ***@***.***>
Verzonden: zondag 16 april 2023 11:19
Aan: marcinbojko/foreman_exporter ***@***.***>
CC: Danny ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [marcinbojko/foreman_exporter] KeyError: 'configuration_status' (Issue #1)


Hi @Fr0zenflame<https://github.com/Fr0zenflame>
Sorry, but currently I don't have much time to play with open source.
I've changed the logic for checks, so please try the new version

https://hub.docker.com/layers/marcinbojko/foreman_exporter/0.0.15-dev.2/images/sha256-79464c46cd8aee885694d33605aa70c70fc31b0cebe1fb9d072247683c34c240?context=repo

**Comment by marcinbojko** [comment]
Please try: 0.0.15-dev.3
Could you provide some logs? Email is fine.
If this doesn't work we need to have a sample from your env, of course, please obfuscate it first :)

**Comment by Fr0zenflame** [comment]
Hi Marcin,

Same for the new image.

I use docker and docker compose to start the image (I dont provide -d) to see the startup output verbose on the console.
In the screenshot below you can see the startup sequence/log

[cid:b3bfdfb9-6295-470f-89fc-c2cee7b708dd]

Afterwards I'am unable to access the container since it crashes and stops after the error.
If I change the API password in the .env file (so it does not work) , the container starts correctly, but then ofc there is no data available since the api is not authorized.

If I need to provide other logs or config please provide which logs u need.
I can look into it tonight or tomorrow 🙂

Kind regards,
Danny.
________________________________
Van: marcinbojko ***@***.***>
Verzonden: zondag 16 april 2023 13:14
Aan: marcinbojko/foreman_exporter ***@***.***>
CC: Danny ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [marcinbojko/foreman_exporter] KeyError: 'configuration_status' (Issue #1)


Please try: 0.0.15-dev.3
Could you provide some logs? Email is fine.
If this doesn't work we need to have a sample from your env, of course, please obfuscate it first :)

**Comment by Fr0zenflame** [comment]
Hi @marcinbojko ,

I cloned you're repo, change some docker related flags an fixed the error I encountered in the script (/app/foreman_exporter.py).
It can deal with "null" values now and as far as I can see it seems to work correctly.

![issue2](https://user-images.githubusercontent.com/107129758/236853783-ea94b5c0-aedb-40ad-8c2f-a8bdb954a694.png)
![issue1](https://user-images.githubusercontent.com/107129758/236853785-0eb8295b-7f95-4d42-92ea-c63992a8941e.png)

We will continue to integrate this into our dev environment and see what happens ^^

**Code change provided below**
[foreman_exporter.txt](https://github.com/marcinbojko/foreman_exporter/files/11422130/foreman_exporter.txt)

**Comment by marcinbojko** [comment]
Hi @Fr0zenflame 
Feel free to prepare PR to dev branch

**Comment by Fr0zenflame** [comment]
> Hi @Fr0zenflame Feel free to prepare PR to dev branch

done :)
